import {
  TenantInfo,
  Firm,
  Godown,
  Category,
  Product,
  Party,
  Invoice,
  ExpenseItem,
  PurchaseInvoice,
  Quotation,
  CreditNote,
  DebitNote,
  StaffUser,
  TenantRegistryItem,
} from "./types";

export const INITIAL_TENANT: TenantInfo = {
  id: "tenant-vyapar-01",
  name: "लेखा जोखा Mega Retail & Wholesale",
  legalName: "लेखा जोखा Enterprise India Pvt Ltd",
  gstin: "27AABCU9603R1ZM",
  stateCode: "27",
  stateName: "Maharashtra",
  phone: "+91 98200 12345",
  email: "billing@lekhajokha.enterprise",
  address: "Shop 104-106, Commercial Arcade, LBS Marg, Ghatkopar West",
  city: "Mumbai",
  pincode: "400086",
  upiVpa: "lekhajokha@icici",
  upiName: "लेखा जोखा Enterprise",
  bankName: "ICICI Bank Ltd",
  bankAccountNumber: "001105023456",
  bankIfsc: "ICIC0000011",
  bankBranch: "Ghatkopar West, Mumbai",
  thermalHeader: "★ लेखा जोखा ENTERPRISE ★\nGSTIN: 27AABCU9603R1ZM | Ph: 9820012345\nTax Invoice / Cash Receipt",
  thermalFooter: "Thank you for shopping with us!\nGoods once sold will not be taken back without bill.\nVisit again! Have a great day.",
  termsAndConditions: "1. All disputes are subject to Mumbai Jurisdiction.\n2. Goods once sold will be exchanged within 7 days in original condition.\n3. Interest @ 18% p.a. will be charged if bill is not settled within credit due date.",
};

export const INITIAL_FIRMS: Firm[] = [
  {
    id: "firm-mum-01",
    tenantId: "tenant-vyapar-01",
    name: "लेखा जोखा Mega Retail & Wholesale",
    legalName: "लेखा जोखा Enterprise India Pvt Ltd",
    gstin: "27AABCU9603R1ZM",
    stateCode: "27",
    stateName: "Maharashtra",
    address: "Shop 104-106, Commercial Arcade, LBS Marg, Ghatkopar West, Mumbai",
    pincode: "400086",
    phone: "+91 98200 12345",
    email: "billing@lekhajokha.enterprise",
    upiId: "lekhajokha@icici",
    bankName: "ICICI Bank Ltd",
    accountNo: "001105023456",
    ifsc: "ICIC0000011",
    invoicePrefix: "LJ-MUM",
    isPrimary: true,
  },
  {
    id: "firm-blr-02",
    tenantId: "tenant-vyapar-01",
    name: "लेखा जोखा Tech & Digital Hub (Karnataka Branch)",
    legalName: "लेखा जोखा South India LLP",
    gstin: "29AAACV5432R1Z2",
    stateCode: "29",
    stateName: "Karnataka",
    address: "Plot 42, Brigade Road, Commercial Hub, Ashok Nagar, Bengaluru",
    pincode: "560025",
    phone: "+91 80 4123 4567",
    email: "blr.billing@lekhajokha.enterprise",
    upiId: "lekhajokha.blr@hdfcbank",
    bankName: "HDFC Bank Ltd",
    accountNo: "50200088991122",
    ifsc: "HDFC0000123",
    invoicePrefix: "LJ-BLR",
    isPrimary: false,
  },
];

export const INITIAL_GODOWNS: Godown[] = [
  { id: "godown-1", tenantId: "tenant-vyapar-01", name: "Store Front Counter", location: "Ground Floor", isDefault: true },
  { id: "godown-2", tenantId: "tenant-vyapar-01", name: "Main Godown - Mumbai", location: "Basement Warehouse", isDefault: false },
  { id: "godown-3", tenantId: "tenant-vyapar-01", name: "Warehouse B - Bhiwandi Hub", location: "Bhiwandi Logistic Park", isDefault: false },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: "cat-pharma", tenantId: "tenant-vyapar-01", name: "Pharma & Healthcare", codePrefix: "PHARM", defaultGstRate: 12.0, hsnCode: "3004", productCount: 0 },
  { id: "cat-fmcg", tenantId: "tenant-vyapar-01", name: "Groceries & FMCG", codePrefix: "FMCG", defaultGstRate: 5.0, hsnCode: "2106", productCount: 0 },
  { id: "cat-elec", tenantId: "tenant-vyapar-01", name: "Electronics & Mobiles", codePrefix: "ELEC", defaultGstRate: 18.0, hsnCode: "8517", productCount: 0 },
  { id: "cat-paints", tenantId: "tenant-vyapar-01", name: "Paints & Hardware", codePrefix: "HARD", defaultGstRate: 28.0, hsnCode: "3208", productCount: 0 },
];

export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_PARTIES: Party[] = [
  {
    id: "party-sharma-med",
    tenantId: "tenant-vyapar-01",
    name: "Sharma Medical & Healthcare Stores",
    type: "CUSTOMER",
    phone: "9820198201",
    email: "sharmamedicals@gmail.com",
    gstin: "27AABCU1234F1Z5",
    stateCode: "27",
    billingAddress: "Shop 12, Shivaji Nagar Market, Pune",
    city: "Pune",
    pincode: "411005",
    creditLimit: 100000,
    openingBalance: 0,
    currentBalance: 0,
  },
  {
    id: "party-apex-karnataka",
    tenantId: "tenant-vyapar-01",
    name: "Apex Electronics & Smart Devices",
    type: "CUSTOMER",
    phone: "9900012345",
    email: "procure@apexelectronics.in",
    gstin: "29AAACP1234G1Z8", // Karnataka Inter-State GSTIN
    stateCode: "29",
    billingAddress: "45, Brigade Road, Ashok Nagar",
    city: "Bengaluru",
    pincode: "560025",
    creditLimit: 500000,
    openingBalance: 0,
    currentBalance: 0,
  },
  {
    id: "party-priya-ent",
    tenantId: "tenant-vyapar-01",
    name: "Priya Supermarket & Wholesale Traders",
    type: "CUSTOMER",
    phone: "9730097300",
    email: "orders@priyasupermarket.com",
    gstin: "27AABCP9988A1Z2",
    stateCode: "27",
    billingAddress: "Plot 88, Central Avenue, Wardha Road",
    city: "Nagpur",
    pincode: "440015",
    creditLimit: 200000,
    openingBalance: 0,
    currentBalance: 0,
  },
  {
    id: "party-walkin-cash",
    tenantId: "tenant-vyapar-01",
    name: "Walk-in Retail Customer (Cash)",
    type: "CUSTOMER",
    phone: "9800000000",
    stateCode: "27",
    billingAddress: "Counter Sale, Mumbai",
    city: "Mumbai",
    pincode: "400086",
    creditLimit: 0,
    openingBalance: 0,
    currentBalance: 0,
  },
  {
    id: "party-reliance-wholsale",
    tenantId: "tenant-vyapar-01",
    name: "Reliance Consumer Products Wholesale Hub",
    type: "VENDOR",
    phone: "022-28490000",
    email: "vendor.desk@ril.com",
    gstin: "27AAACR5055K1Z3",
    stateCode: "27",
    billingAddress: "Reliance Corporate Park, Ghansoli",
    city: "Navi Mumbai",
    pincode: "400701",
    creditLimit: 1000000,
    openingBalance: 0,
    currentBalance: 0,
  },
];

export const INITIAL_INVOICES: Invoice[] = [];

export const INITIAL_EXPENSES: ExpenseItem[] = [];

export const INITIAL_PURCHASES: PurchaseInvoice[] = [];

export const INITIAL_QUOTATIONS: Quotation[] = [];

export const INITIAL_CREDIT_NOTES: CreditNote[] = [];

export const INITIAL_DEBIT_NOTES: DebitNote[] = [];

export const INITIAL_STAFF = [
  {
    id: "usr-admin-01",
    tenantId: "tenant-vyapar-01",
    name: "Rajesh Sharma (Owner)",
    email: "admin@vyaparflow.enterprise",
    phone: "9820012345",
    role: "TENANT_OWNER" as const,
    password: "admin",
    pin: "1234",
    isActive: true,
    permissions: {
      canEditBackdatedInvoices: true,
      canViewPurchaseRates: true,
      canViewProfitMargins: true,
      canGiveBillDiscounts: true,
      canDeleteInvoices: true,
      canManageUsers: true,
      canAccessSettings: true,
    },
    createdAt: "2026-08-01",
  },
  {
    id: "usr-mgr-02",
    tenantId: "tenant-vyapar-01",
    name: "Amit Patel (Senior Accountant)",
    email: "accountant@vyaparflow.enterprise",
    phone: "9820023456",
    role: "ACCOUNTANT" as const,
    password: "password123",
    pin: "2345",
    isActive: true,
    permissions: {
      canEditBackdatedInvoices: false,
      canViewPurchaseRates: true,
      canViewProfitMargins: true,
      canGiveBillDiscounts: true,
      canDeleteInvoices: false,
      canManageUsers: false,
      canAccessSettings: true,
    },
    createdAt: "2026-08-10",
  },
  {
    id: "usr-csh-03",
    tenantId: "tenant-vyapar-01",
    name: "Suresh Kumar (Cashier Counter 1)",
    email: "cashier@vyaparflow.enterprise",
    phone: "9820034567",
    role: "CASHIER" as const,
    password: "password123",
    pin: "3456",
    isActive: true,
    permissions: {
      canEditBackdatedInvoices: false,
      canViewPurchaseRates: false,
      canViewProfitMargins: false,
      canGiveBillDiscounts: false,
      canDeleteInvoices: false,
      canManageUsers: false,
      canAccessSettings: false,
    },
    createdAt: "2026-09-01",
  },
  {
    id: "usr-inv-04",
    tenantId: "tenant-vyapar-01",
    name: "Vikas Mehra (Inventory Storekeeper)",
    email: "inventory@vyaparflow.enterprise",
    phone: "9820045678",
    role: "STOREKEEPER" as const,
    password: "password123",
    pin: "4567",
    isActive: true,
    permissions: {
      canEditBackdatedInvoices: false,
      canViewPurchaseRates: true,
      canViewProfitMargins: false,
      canGiveBillDiscounts: false,
      canDeleteInvoices: false,
      canManageUsers: false,
      canAccessSettings: false,
    },
    createdAt: "2026-09-02",
  },
];

export const SUPER_ADMIN_USER: StaffUser = {
  id: "usr-superadmin-00",
  name: "Platform Architect (Super Admin)",
  email: "superadmin@vyaparflow.enterprise",
  phone: "+91 99000 00000",
  role: "SUPER_ADMIN",
  password: "superadmin123",
  pin: "9999",
  isActive: true,
  permissions: {
    canEditBackdatedInvoices: true,
    canViewPurchaseRates: true,
    canViewProfitMargins: true,
    canGiveBillDiscounts: true,
    canDeleteInvoices: true,
    canManageUsers: true,
    canAccessSettings: true,
  },
  createdAt: "2026-01-01",
};

export const INITIAL_TENANTS_REGISTRY: TenantRegistryItem[] = [
  {
    id: "tenant-vyapar-01",
    name: "लेखा जोखा Enterprise Retail & Wholesale",
    legalName: "लेखा जोखा Enterprise India Pvt Ltd",
    gstin: "27AABCU9603R1ZM",
    stateCode: "27",
    stateName: "Maharashtra",
    plan: "ENTERPRISE",
    isActive: true,
    ownerName: "Rajesh Sharma",
    ownerEmail: "admin@vyaparflow.enterprise",
    ownerPhone: "+91 98200 12345",
    totalUsersCount: 4,
    createdAt: "2026-08-01",
    lastActiveAt: "2026-09-07T14:30:00Z",
  },
  {
    id: "tenant-apollo-02",
    name: "Apollo Chemist & Surgical Mart",
    legalName: "Apollo MedCare Retailers LLP",
    gstin: "29AAACA1234R1Z5",
    stateCode: "29",
    stateName: "Karnataka",
    plan: "PRO",
    isActive: true,
    ownerName: "Dr. Arvind Rao",
    ownerEmail: "arvind@apollopharm.in",
    ownerPhone: "+91 98450 67890",
    totalUsersCount: 3,
    createdAt: "2026-08-15",
    lastActiveAt: "2026-09-07T12:15:00Z",
  },
  {
    id: "tenant-techworld-03",
    name: "TechWorld Mobiles & Electronics",
    legalName: "TechWorld Retail Hub",
    gstin: "07AABCT9988R1Z1",
    stateCode: "07",
    stateName: "Delhi",
    plan: "PRO",
    isActive: true,
    ownerName: "Vikas Aggarwal",
    ownerEmail: "vikas@techworld.delhi",
    ownerPhone: "+91 98110 54321",
    totalUsersCount: 2,
    createdAt: "2026-08-20",
    lastActiveAt: "2026-09-06T18:45:00Z",
  },
  {
    id: "tenant-royalsilks-04",
    name: "Royal Silks & Sarees Emporium",
    legalName: "Royal Heritage Textiles",
    gstin: "33AABCR4455R1Z9",
    stateCode: "33",
    stateName: "Tamil Nadu",
    plan: "STARTER",
    isActive: false,
    ownerName: "Sundaram Ramanathan",
    ownerEmail: "sundaram@royalsilks.tn",
    ownerPhone: "+91 94440 11223",
    totalUsersCount: 1,
    createdAt: "2026-08-25",
    lastActiveAt: "2026-09-01T10:00:00Z",
  },
];

